# One-shot encoding repair for phase C tier-1 docs (game-phase.md, mapping.md).
param(
    [string[]]$Paths = @(
        (Join-Path (Join-Path $PSScriptRoot '..') 'docs\02-systems\game-phase.md'),
        (Join-Path (Join-Path $PSScriptRoot '..') 'docs\02-systems\mapping.md')
    )
)

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
$fffd = [char]0xFFFD
$arr = [char]0x2192   # right arrow
$em = [char]0x2014    # em dash
$en = [char]0x2013    # en dash
$ell = [char]0x2026    # ellipsis
$sect = [char]0x00A7  # section sign

function Fix-DocEncoding([string]$content) {
    $content = $content.Replace("spec$fffd" + 'd', "spec'd")
    $content = $content.Replace("party$fffd" + 's', "party's")
    $content = $content.Replace("$fffd" + '7)', "$sect" + '7)')
    $content = $content.Replace("$fffd" + 'return to hub.' + "$fffd", "'return to hub.'")
    $content = $content.Replace("$fffd" + 'hub only.' + "$fffd", "'hub only.'")
    $content = $content.Replace("$fffd" + '"another stalker on the map"' + "$fffd", '"another stalker on the map"')
    $content = $content.Replace("$fffd" + 'incoming FOE' + "$fffd", "'incoming FOE'")
    $content = $content.Replace('[? Consider', "[$sect Consider")
    $content = $content.Replace('? Consider / explore', "$sect Consider / explore")
    $content = $content.Replace("ContentDatabase, $fffd", "ContentDatabase, $ell")
    $content = $content.Replace('ContentDatabase, ?', "ContentDatabase, $ell")
    $content = $content.Replace('F1?F4', "F1$en" + 'F4')
    $content = $content.Replace("F1$fffd" + 'F4', "F1$en" + 'F4')
    $content = $content.Replace("GamePhaseController.cs $fffd plain", "GamePhaseController.cs $em plain")
    $content = $content.Replace('GamePhaseController.cs ? plain', "GamePhaseController.cs $em plain")

    $pairs = @(
        ,@("turn) ? end-of-round", "turn) $arr end-of-round")
        ,@("turn) $fffd end-of-round", "turn) $arr end-of-round")
        ,@('+-- GamePhaseController          ? authoritative', "+-- GamePhaseController          $em authoritative")
        ,@('+-- HubPhaseController           ? IPhaseController', "+-- HubPhaseController           $em IPhaseController")
        ,@('+-- ExplorationPhaseController ? IPhaseController', "+-- ExplorationPhaseController $em IPhaseController")
        ,@('+-- CombatPhaseController        ? IPhaseController', "+-- CombatPhaseController        $em IPhaseController")
        ,@('GameBootstrap (UI)               ? InputRouter', "GameBootstrap (UI)               $em InputRouter")
        ,@('InputRouter                      ? enables', "InputRouter                      $em enables")
        ,@("StartBattle` $fffd does", "StartBattle` $em does")
        ,@('StartBattle` ? does', "StartBattle` $em does")
        ,@("victory $fffd **unchanged", "victory $em **unchanged")
        ,@('victory ? **unchanged', "victory $em **unchanged")
        ,@("Planned $fffd dev boot", "Planned $em dev boot")
        ,@('Planned ? dev boot', "Planned $em dev boot")
        ,@("Partial $fffd dev hardcodes", "Partial $em dev hardcodes")
        ,@('Partial ? dev hardcodes', "Partial $em dev hardcodes")
        ,@('Bootstrap ? `s1_B1F`', "Bootstrap $arr ``s1_B1F``")
        ,@('LeaveHub` ? S1:', "LeaveHub` $em S1:")
        ,@('`LeaveHub` ? `RequestTransition', "``LeaveHub`` $arr ``RequestTransition")
        ,@("EnterSideDungeon` $fffd spawn", "EnterSideDungeon` $arr spawn")
        ,@('EnterSideDungeon` ? spawn', "EnterSideDungeon` $arr spawn")
        ,@('(gate) ? camp', "(gate) $arr camp")
        ,@('interact ? `GameState`', "interact $arr ``GameState``")
        ,@("interact $fffd **hub only**", "interact $arr **hub only**")
        ,@('interact ? **hub only**', "interact $arr **hub only**")
        ,@('Controller` ? `GameState', "Controller`` $arr ``GameState")
        ,@("**event** $fffd not exploration pause", "**event** $em not exploration pause")
        ,@('**event** ? not exploration pause', "**event** $em not exploration pause")
        ,@('**pause** ? title', "**pause** $arr title")
        ,@('`Esc` ? confirm', "``Esc`` $arr confirm")
        ,@("on flee $fffd only Exploration", "on flee $em only Exploration")
        ,@('on flee ? only Exploration', "on flee $em only Exploration")
        ,@('**Combat ? Hub**', "**Combat $arr Hub**")
        ,@("events $fffd S1 flow", "events $em S1 flow")
        ,@('events ? S1 flow', "events $em S1 flow")
        ,@(")) $fffd not victory", ")) $em not victory")
        ,@(')) ? not victory', ")) $em not victory")
        ,@("**FOE contact** $fffd if", "**FOE contact** $em if")
        ,@('**FOE contact** ? if', "**FOE contact** $em if")
        ,@("**Random encounter** $fffd ``EncounterTrigger", "**Random encounter** $em ``EncounterTrigger")
        ,@('**Random encounter** ? `EncounterTrigger', "**Random encounter** $em ``EncounterTrigger")
        ,@("boot** $fffd **If", "boot** $em **If")
        ,@('boot** ? **If', "boot** $em **If")
        ,@('`InputRouter` ? `UI`', "``InputRouter`` $arr ``UI``")
        ,@('OnFoeContact` ? `RequestCombat`', "OnFoeContact`` $arr ``RequestCombat``")
        ,@("progression $fffd Skill points", "progression $em Skill points")
        ,@('progression ? Skill points', "progression $em Skill points")
        ,@("Yes $fffd Explorers", "Yes $em Explorers")
        ,@('Yes ? Explorers', "Yes $em Explorers")
        ,@("Yes $fffd ``Tab``", "Yes $em ``Tab``")
        ,@('Yes ? `Tab`', "Yes $em ``Tab``")
        ,@("**No** $fffd including", "**No** $em including")
        ,@('**No** ? including', "**No** $em including")
        ,@("gates $fffd not", "gates $em not")
        ,@('gates ? not', "gates $em not")
        ,@('GridDungeon ? Scenes', "GridDungeon $arr Scenes")
        ,@("repo $fffd run after clone", "repo $em run after clone")
        ,@('repo ? run after clone', "repo $em run after clone")
        ,@("Settings** $fffd wired", "Settings** $em wired")
        ,@('Settings** ? wired', "Settings** $em wired")
        ,@('clicked` ? `GameState', "clicked`` $arr ``GameState")
        ,@("game $fffd mirrored", "game $em mirrored")
        ,@('game ? mirrored', "game $em mirrored")
        ,@('F1 Hub ? F2', "F1 Hub $arr F2")
        ,@("AGI 5) $fffd for turn-order", "AGI 5) $em for turn-order")
        ,@('AGI 5) ? for turn-order', "AGI 5) $em for turn-order")
        ,@("authoritative $fffd it only", "authoritative $em it only")
        ,@('authoritative ? it only', "authoritative $em it only")
        ,@("exploration-ui.md) $fffd UXML", "exploration-ui.md) $em UXML")
        ,@('exploration-ui.md) ? UXML', "exploration-ui.md) $em UXML")
        ,@("[ADR 022 $fffd Side", "[ADR 022 $em Side")
        ,@('[ADR 022 ? Side', "[ADR 022 $em Side")
        ,@("exploration-ui.md) $fffd ``ExplorationMapCoordinator``", "exploration-ui.md) $em ``ExplorationMapCoordinator``")
        ,@('exploration-ui.md) ? `ExplorationMapCoordinator`', "exploration-ui.md) $em ``ExplorationMapCoordinator``")
        ,@("revealed state $fffd authored", "revealed state $em authored")
        ,@('revealed state ? authored', "revealed state $em authored")
        ,@('Floor Editor** ? SO', "Floor Editor** $arr SO")
        ,@("tech notes $fffd UI reactivity", "tech notes $em UI reactivity")
        ,@('tech notes ? UI reactivity', "tech notes $em UI reactivity")
        ,@("| Yes $fffd with step beat", "| Yes $em with step beat")
        ,@('| Yes ? with step beat', "| Yes $em with step beat")
        ,@("| Yes $fffd with interact beat", "| Yes $em with interact beat")
        ,@('| Yes ? with interact beat', "| Yes $em with interact beat")
        ,@("| Yes $fffd before next step", "| Yes $em before next step")
        ,@('| Yes ? before next step', "| Yes $em before next step")
        ,@("| No $fffd ambient", "| No $em ambient")
        ,@('| No ? ambient', "| No $em ambient")
        ,@("| Yes $fffd with step lerp", "| Yes $em with step lerp")
        ,@('| Yes ? with step lerp', "| Yes $em with step lerp")
        ,@("| Yes $fffd before next interact", "| Yes $em before next interact")
        ,@('| Yes ? before next interact', "| Yes $em before next interact")
        ,@("| No $fffd overlay only", "| No $em overlay only")
        ,@('| No ? overlay only', "| No $em overlay only")
        ,@('in place** ? chart', "in place** $arr chart")
        ,@('blocked side ? stamp', "blocked side $arr stamp")
        ,@('turn** ? solid', "turn** $arr solid")
        ,@("015-mvp1-combat.md)) $fffd ambient", "015-mvp1-combat.md)) $em ambient")
        ,@('015-mvp1-combat.md)) ? ambient', "015-mvp1-combat.md)) $em ambient")
        ,@("**A $fffd Persistent", "**A $em Persistent")
        ,@('**A ? Persistent', "**A $em Persistent")
        ,@("hidden $fffd panel", "hidden $em panel")
        ,@('hidden ? panel', "hidden $em panel")
        ,@("**B $fffd Compact", "**B $em Compact")
        ,@('**B ? Compact', "**B $em Compact")
        ,@("**C $fffd ``M``", "**C $em ``M``")
        ,@('**C ? `M`', "**C $em ``M``")
        ,@("**D $fffd Threat", "**D $em Threat")
        ,@('**D ? Threat', "**D $em Threat")
        ,@("design $fffd View controllers", "design $em View controllers")
        ,@('design ? View controllers', "design $em View controllers")
        ,@("combat-scene.md)) $fffd map shows", "combat-scene.md)) $em map shows")
        ,@('combat-scene.md)) ? map shows', "combat-scene.md)) $em map shows")
        ,@("state only $fffd no player", "state only $em no player")
        ,@('state only ? no player', "state only $em no player")
        ,@("alcove $fffd not 16", "alcove $em not 16")
        ,@('alcove ? not 16', "alcove $em not 16")
        ,@('fog ? solid', "fog $arr solid")
        ,@('(3+ ? `', "(3+ $arr ``")
        ,@("(3+ $fffd ``", "(3+ $arr ``")
        ,@(') ? features', ") $arr features")
        ,@(') ? floor', ") $arr floor")
        ,@("labels $fffd they live", "labels $em they live")
        ,@('labels ? they live', "labels $em they live")
        ,@("UI $fffd Map marker", "UI $em Map marker")
        ,@('UI ? Map marker', "UI $em Map marker")
        ,@('bottom ? top', "bottom $arr top")
        ,@('gather ? hub', "gather $arr hub")
        ,@('hub-gate ? FOE', "hub-gate $arr FOE")
        ,@('FOE ? party', "FOE $arr party")
        ,@("[Refs $fffd Map UI", "[Refs $em Map UI")
        ,@('[Refs ? Map UI', "[Refs $em Map UI")
        ,@("map-ui.md) $fffd inspiration", "map-ui.md) $em inspiration")
        ,@('map-ui.md) ? inspiration', "map-ui.md) $em inspiration")
        ,@("map-cell-art.md) $fffd sprites", "map-cell-art.md) $em sprites")
        ,@('map-cell-art.md) ? sprites', "map-cell-art.md) $em sprites")
        ,@("save-format.md) $fffd packing", "save-format.md) $em packing")
        ,@('save-format.md) ? packing', "save-format.md) $em packing")
        ,@("[02 $fffd Dungeon", "[02 $em Dungeon")
        ,@('[02 ? Dungeon', "[02 $em Dungeon")
        ,@("foe-encounters.md) $fffd [Chain", "foe-encounters.md) $em [Chain")
        ,@('foe-encounters.md) ? [Chain', "foe-encounters.md) $em [Chain")
        ,@("exploration-ui.md) $fffd HUD", "exploration-ui.md) $em HUD")
        ,@('exploration-ui.md) ? HUD', "exploration-ui.md) $em HUD")
        ,@("combat-scene.md) $fffd [Game", "combat-scene.md) $em [Game")
        ,@('combat-scene.md) ? [Game', "combat-scene.md) $em [Game")
        ,@("[ADR 002 $fffd Mapping", "[ADR 002 $em Mapping")
        ,@('[ADR 002 ? Mapping', "[ADR 002 $em Mapping")
        ,@("[ADR 005 $fffd FOE", "[ADR 005 $em FOE")
        ,@('[ADR 005 ? FOE', "[ADR 005 $em FOE")
        ,@("patrol.md) $fffd [ADR 014", "patrol.md) $em [ADR 014")
        ,@('patrol.md) ? [ADR 014', "patrol.md) $em [ADR 014")
        ,@("[ADR 014 $fffd launch", "[ADR 014 $em launch")
        ,@('[ADR 014 ? launch', "[ADR 014 $em launch")
        ,@("[ADR 019 $fffd Floor", "[ADR 019 $em Floor")
        ,@('[ADR 019 ? Floor', "[ADR 019 $em Floor")
        ,@("[04 $fffd Tech", "[04 $em Tech")
        ,@('[04 ? Tech', "[04 $em Tech")
        ,@("events ? ``MapSystem``", "events $arr ``MapSystem``")
        ,@("events $fffd ``MapSystem``", "events $arr ``MapSystem``")
        ,@("LeaveHub` $fffd S1:", "LeaveHub` $em S1:")
    )

    foreach ($pair in $pairs) {
        $content = $content.Replace($pair[0], $pair[1])
    }

    $content = $content.Replace("(3+ $arr ``$fffd``)", "(3+ $arr ``?``)")
    $content = $content.Replace("floor ``$fffd``", 'floor `?`')

    if ($content.IndexOf($fffd) -ge 0) {
        $content = $content.Replace([string]$fffd, [string]$em)
    }

    return $content
}

foreach ($path in $Paths) {
    $full = [System.IO.Path]::GetFullPath($path)
    if (-not (Test-Path $full)) {
        Write-Warning "Skip missing: $full"
        continue
    }
    $before = [System.IO.File]::ReadAllText($full)
    $after = Fix-DocEncoding $before
    if ($before -ne $after) {
        [System.IO.File]::WriteAllText($full, $after, $utf8NoBom)
        Write-Host "Fixed: $full"
    }
    else {
        Write-Host "No changes: $full"
    }
}
